[tool.poetry]
name = "sql_metadata"
version = "1.10.0"
license="MIT"
description = "Uses tokenized query returned by python-sqlparse and generates query metadata"
authors = ["macbre <maciej.brencz@bethink.pl>"]

[tool.poetry.dependencies]
python = "^3.8"
sqlparse = "^0.4.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.4"
pylint = "^2.6.0"
pytest = "^6.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
